=== jan-gliniorz/swa/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    adresse*,
    artikel*,
    auftrag*,
    auftragsposition*,
    hibernate_sequence*,
    kunde*,
    lager*,
    lagerposition*,
    lieferung*,
    lieferungsposition*,
    rechnung*)>

<!ELEMENT adresse EMPTY>
<!ATTLIST adresse
    adresse_ID CDATA #REQUIRED
    strasse CDATA #REQUIRED
    hausNr CDATA #REQUIRED
    plz CDATA #REQUIRED
    ort CDATA #REQUIRED
    land CDATA #REQUIRED
    kunde_FID CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT artikel EMPTY>
<!ATTLIST artikel
    artikel_ID CDATA #REQUIRED
    bezeichung CDATA #REQUIRED
    beschreibung CDATA #IMPLIED
    preis CDATA #REQUIRED
    bild CDATA #IMPLIED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT auftrag EMPTY>
<!ATTLIST auftrag
    auftrag_ID CDATA #REQUIRED
    kunde_FID CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT auftragsposition EMPTY>
<!ATTLIST auftragsposition
    auftragsposition_ID CDATA #REQUIRED
    artikel_FID CDATA #REQUIRED
    auftrag_FID CDATA #REQUIRED
    anzahl CDATA #REQUIRED
    preis CDATA #REQUIRED
>

<!ELEMENT hibernate_sequence EMPTY>
<!ATTLIST hibernate_sequence
    next_val CDATA #REQUIRED
>

<!ELEMENT kunde EMPTY>
<!ATTLIST kunde
    kundenNr CDATA #REQUIRED
    nachname CDATA #REQUIRED
    vorname CDATA #REQUIRED
    email CDATA #REQUIRED
    passwort CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT lager EMPTY>
<!ATTLIST lager
    lager_ID CDATA #REQUIRED
    bezeichung CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT lagerposition EMPTY>
<!ATTLIST lagerposition
    lagerposition_ID CDATA #REQUIRED
    lager_FID CDATA #REQUIRED
    artikel_FID CDATA #REQUIRED
    anzahl CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT lieferung EMPTY>
<!ATTLIST lieferung
    lieferung_ID CDATA #REQUIRED
    bestelldatum CDATA #REQUIRED
    lieferungsdatum CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

<!ELEMENT lieferungsposition EMPTY>
<!ATTLIST lieferungsposition
    lieferungsposition_ID CDATA #REQUIRED
    artikel_FID CDATA #REQUIRED
    lieferung_FID CDATA #REQUIRED
    anzahl CDATA #REQUIRED
>

<!ELEMENT rechnung EMPTY>
<!ATTLIST rechnung
    rechnung_ID CDATA #REQUIRED
    auftrag_FID CDATA #REQUIRED
    rechnungsdatum CDATA #REQUIRED
    erstellt_am CDATA #REQUIRED
    geaendert_am CDATA #REQUIRED
>

=== jan-gliniorz/swa/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <adresse adresse_ID="100" strasse="Kaiserstrasse" hausNr="234" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="10" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="101" strasse="Ringstrasse" hausNr="10" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="11" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="102" strasse="Lilienstrasse" hausNr="90" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="12" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="103" strasse="Fischerweg" hausNr="7" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="13" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="104" strasse="Karlstrasse" hausNr="56" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="14" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="105" strasse="Blumenweg" hausNr="2" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="15" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="106" strasse="Herrenstrasse" hausNr="34" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="16" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="107" strasse="Kronenweg32" hausNr="234" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="17" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="108" strasse="Lessingstrasse" hausNr="15" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="18" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <adresse adresse_ID="109" strasse="Kaiserstrasse" hausNr="40" plz="76133" ort="Karlsruhe" land="Deutschland" kunde_FID="19" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <artikel artikel_ID="300" bezeichung="Chino" beschreibung="Hose" preis="50" bild="x" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <artikel artikel_ID="301" bezeichung="Hemd" beschreibung="Hemd" preis="25" bild="x" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <artikel artikel_ID="302" bezeichung="T-Shirt" beschreibung="T-Shirt" preis="15" bild="x" erstellt_am="2011-10-03 00:00:00.0" geaendert_am="2011-10-03 00:00:00.0"/>
  <artikel artikel_ID="303" bezeichung="Woll-Pullover" beschreibung="Pullover" preis="35" bild="x" erstellt_am="2011-10-03 00:00:00.0" geaendert_am="2011-10-03 00:00:00.0"/>
  <artikel artikel_ID="304" bezeichung="Regenjacke" beschreibung="Jacke" preis="50" bild="x" erstellt_am="2011-10-07 00:00:00.0" geaendert_am="2011-10-07 00:00:00.0"/>
  <artikel artikel_ID="305" bezeichung="Sakko" beschreibung="Sakko" preis="55" bild="x" erstellt_am="2011-10-07 00:00:00.0" geaendert_am="2011-10-07 00:00:00.0"/>
  <artikel artikel_ID="306" bezeichung="Weste" beschreibung="Weste" preis="25" bild="x" erstellt_am="2011-10-07 00:00:00.0" geaendert_am="2011-10-07 00:00:00.0"/>
  <artikel artikel_ID="307" bezeichung="Boxershort" beschreibung="Unterw" preis="5" bild="x" erstellt_am="2011-10-10 00:00:00.0" geaendert_am="2011-10-10 00:00:00.0"/>
  <artikel artikel_ID="308" bezeichung="Badeshort" beschreibung="Badehose" preis="10" bild="x" erstellt_am="2011-10-10 00:00:00.0" geaendert_am="2011-10-10 00:00:00.0"/>
  <artikel artikel_ID="309" bezeichung="Jogginghose" beschreibung="Sporthose" preis="23" bild="x" erstellt_am="2011-10-10 00:00:00.0" geaendert_am="2011-10-10 00:00:00.0"/>
  <auftrag auftrag_ID="150" kunde_FID="10" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <auftrag auftrag_ID="151" kunde_FID="10" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <auftrag auftrag_ID="152" kunde_FID="11" erstellt_am="2011-10-03 00:00:00.0" geaendert_am="2011-10-03 00:00:00.0"/>
  <auftrag auftrag_ID="153" kunde_FID="12" erstellt_am="2011-10-03 00:00:00.0" geaendert_am="2011-10-03 00:00:00.0"/>
  <auftrag auftrag_ID="154" kunde_FID="10" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="155" kunde_FID="10" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="156" kunde_FID="12" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="157" kunde_FID="13" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="158" kunde_FID="14" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="159" kunde_FID="14" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftrag auftrag_ID="160" kunde_FID="15" erstellt_am="2011-10-04 00:00:00.0" geaendert_am="2011-10-04 00:00:00.0"/>
  <auftragsposition auftragsposition_ID="200" artikel_FID="150" auftrag_FID="300" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="201" artikel_FID="150" auftrag_FID="301" anzahl="2" preis="21"/>
  <auftragsposition auftragsposition_ID="202" artikel_FID="151" auftrag_FID="302" anzahl="2" preis="21"/>
  <auftragsposition auftragsposition_ID="203" artikel_FID="152" auftrag_FID="305" anzahl="20" preis="21"/>
  <auftragsposition auftragsposition_ID="204" artikel_FID="153" auftrag_FID="300" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="205" artikel_FID="153" auftrag_FID="303" anzahl="3" preis="21"/>
  <auftragsposition auftragsposition_ID="206" artikel_FID="153" auftrag_FID="304" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="207" artikel_FID="153" auftrag_FID="309" anzahl="10" preis="21"/>
  <auftragsposition auftragsposition_ID="208" artikel_FID="153" auftrag_FID="308" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="209" artikel_FID="154" auftrag_FID="305" anzahl="4" preis="21"/>
  <auftragsposition auftragsposition_ID="210" artikel_FID="155" auftrag_FID="309" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="211" artikel_FID="156" auftrag_FID="307" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="212" artikel_FID="157" auftrag_FID="306" anzahl="2" preis="21"/>
  <auftragsposition auftragsposition_ID="213" artikel_FID="158" auftrag_FID="300" anzahl="1" preis="21"/>
  <auftragsposition auftragsposition_ID="214" artikel_FID="159" auftrag_FID="303" anzahl="1" preis="21"/>
  <hibernate_sequence next_val="1000"/>
  <kunde kundenNr="10" nachname="Loyality" vorname="Holly" adresse_FID="100" email="Loya@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="11" nachname="Alan" vorname="Ada" adresse_FID="101" email="Allan@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="12" nachname="Boss" vorname="Joanna" adresse_FID="102" email="Boss@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="13" nachname="Sutphin" vorname="Tamara" adresse_FID="103" email="Sutphin@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="14" nachname="Timberlake" vorname="Dora" adresse_FID="104" email="Timberlake@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="15" nachname="Hooks" vorname="Rodney" adresse_FID="105" email="Hooks@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="16" nachname="Keegan" vorname="Raymond" adresse_FID="106" email="Keegan@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="17" nachname="Jost" vorname="Sonya" adresse_FID="107" email="Jost@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="18" nachname="Parsley" vorname="Marsha" adresse_FID="108" email="Parsley@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <kunde kundenNr="19" nachname="Whitmore" vorname="Paula" adresse_FID="109" email="Whitmore@gmail.com" passwort="1234" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <lager lager_ID="350" bezeichung="L0" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <lager lager_ID="351" bezeichung="L1" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
  <lager lager_ID="352" bezeichung="L2" erstellt_am="2011-10-06 00:00:00.0" geaendert_am="2011-10-06 00:00:00.0"/>
  <lager lager_ID="353" bezeichung="L3" erstellt_am="2011-10-06 00:00:00.0" geaendert_am="2011-10-06 00:00:00.0"/>
  <lager lager_ID="354" bezeichung="L4" erstellt_am="2011-10-06 00:00:00.0" geaendert_am="2011-10-06 00:00:00.0"/>
  <lager lager_ID="355" bezeichung="L5" erstellt_am="2011-10-13 00:00:00.0" geaendert_am="2011-10-13 00:00:00.0"/>
  <lager lager_ID="356" bezeichung="L6" erstellt_am="2011-10-13 00:00:00.0" geaendert_am="2011-10-13 00:00:00.0"/>
  <lager lager_ID="357" bezeichung="L7" erstellt_am="2011-10-13 00:00:00.0" geaendert_am="2011-10-13 00:00:00.0"/>
  <lager lager_ID="358" bezeichung="L8" erstellt_am="2011-10-17 00:00:00.0" geaendert_am="2011-10-17 00:00:00.0"/>
  <lager lager_ID="359" bezeichung="L9" erstellt_am="2011-10-17 00:00:00.0" geaendert_am="2011-10-17 00:00:00.0"/>
  <lagerposition lagerposition_ID="400" lager_FID="350" artikel_FID="300" anzahl="50" erstellt_am="2011-10-01 00:00:00.0" geaendert_am="2011-10-01 00:00:00.0"/>
